version: '3.8'

services:
  # ğŸ˜ Banco de Dados para salvar histÃ³rico e links
  postgres:
    image: postgres:15-alpine
    container_name: pdf_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: pdf_hunter_db
    ports:
      - "1234:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # âš¡ Redis para Fila (Queue) e Cache
  redis:
    image: redis:alpine
    container_name: pdf_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes # PersistÃªncia de dados
    volumes:
      - redisdata:/data

  # ğŸ› ï¸ (Opcional) Interface visual para ver o Redis (tipo um Workbench)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: pdf_redis_gui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  pgdata:
  redisdata: